### PR TITLE
feat: [sc-2874] Update config for Ghost so it sends two variations of prices

### PR DESCRIPTION
**Pull request by teghnet**
Story details: https://app.shortcut.com/chronicle-labs/story/2874

### CODE REVIEW

**Review by deep-quality-dev — APPROVED** [review]
Configs work well, for what do we need to send these two prices? with slash or without slash.

**Comment by deep-quality-dev** [comment]
Because of adding new data models dynamically in gofer, unit test is failing.`TestNewModelsCmd_List`

**Comment by teghnet** [comment]
> Configs work well, for what do we need to send these two prices? with slash or without slash.

We need two signatures one for legacy one for new.

**Comment by teghnet** [comment]
Sorry @deep-quality-dev, this will break #201

**Review by deep-quality-dev — APPROVED** [review]

**Pull request merged**
